### ISSUE TITLE
Update generator

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#127]
This should use v3.1, and the new `fromAST`/`stringify` APIs.

Still TODO:

- [x] Patch `Input.stringify()` to escape `]` in strings
- [x] Patch `Label.stringify()` to escape syntax there too (see #138)
- [x] Patch `fromJSON` to fix menu options (`_mouse_`, `_myself_`, `_stage_`, `_edge_`, `_random_`)
- [x] Add language dropdown to generator page (ref #33)
- [x] Patch `build_translations.py` so that `dropdown_values` is a dictionary, instead of an array (this will make it less fragile)
- [x] Translate menu options inside `fromJSON` (ref #145)

**Comment by tjvr** [comment]
This should work now (sorta). Let me know if you spot any problems.

**Comment by tjvr** [comment]
Everything above is done.
